import { sanitizeText, sanitizeUrl } from '@crawlmouse/engine';

/**
 * SPEC 05 §8/§9.3 — the honest, non-promissory note carried in the generated llms.txt header. Same
 * substance as the in-product llms.txt badge (§8): the file is not consumed by AI search engines; it is
 * read mainly by AI coding agents. NEVER a ranking/citation claim (A16).
 */
export const LLMS_TXT_HONEST_NOTE =
  "No AI search engine consumes this file as of 2026 — Google's own guidance says it isn't needed; it's read mainly by AI coding agents.";

export interface LlmsTxtPage {
  url: string;
  title: string | null;
  pagerank: number | null;
}

/** Crawled title -> a markdown-link label that cannot break the `[label]` syntax: strip control chars +
 *  backticks + collapse whitespace (shared engine escaper), then drop `[`/`]`. Falls back to the url when
 *  empty — and the url-fallback is bracket-stripped too (a "]" in a url would otherwise close the label). */
function label(title: string | null, url: string): string {
  const t = (title ? sanitizeText(title, 120) : '').replace(/[[\]]/g, '');
  return t || sanitizeUrl(url).replace(/[[\]]/g, '');
}

/** Crawled url -> a markdown link target that cannot break the `(target)` syntax: strip control/ws/backticks
 *  (shared engine escaper), then percent-encode parens so a raw ")" can't prematurely close the target. */
function target(url: string): string {
  return sanitizeUrl(url).replace(/\(/g, '%28').replace(/\)/g, '%29');
}

/**
 * §9.3 — deterministically compile an llms.txt artifact from the site's persisted pages, ordered by internal
 * PageRank desc (URL asc tiebreak) so the most-linked hubs lead. Generated in-response, never stored; pure
 * and byte-identical for identical input (R1). Crawled title/url are DATA, escaped at every boundary (A14).
 */
export function buildLlmsTxt(siteUrl: string, pages: LlmsTxtPage[]): string {
  let host: string;
  try {
    host = new URL(siteUrl).host;
  } catch {
    host = sanitizeText(siteUrl, 120);
  }
  const ordered = [...pages].sort(
    (a, b) => (b.pagerank ?? -Infinity) - (a.pagerank ?? -Infinity) || (a.url < b.url ? -1 : a.url > b.url ? 1 : 0),
  );
  return [
    `# ${host}`,
    '',
    "> Generated by Crawlmouse from this site's internal link graph — most-linked pages first.",
    `> ${LLMS_TXT_HONEST_NOTE}`,
    '',
    '## Pages',
    '',
    ...ordered.map((pg) => `- [${label(pg.title, pg.url)}](${target(pg.url)})`),
    '',
  ].join('\n');
}
