-- Provision a public.users row for every Supabase auth user.
--
-- Bug this fixes: nothing created public.users rows on sign-up. Every downstream
-- check (users_self_read RLS, userIsPro, and especially the Stripe entitlement
-- webhook, which UPDATEs users by id / stripe_customer_id) assumed a row keyed on
-- auth.uid() existed. With no row, the webhook's UPDATE matched zero rows and Pro
-- was never granted. This trigger is the standard Supabase pattern and enforces the
-- users.id == auth.uid() invariant the whole app relies on.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
begin
  insert into public.users (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- The trigger fires under the table owner regardless of EXECUTE grants, so revoke the
-- function from the API roles — it must not be callable directly via /rest/v1/rpc.
revoke all on function public.handle_new_user() from public, anon, authenticated;

-- Backfill any existing auth users that predate the trigger.
insert into public.users (id, email)
select id, email from auth.users
on conflict (id) do nothing;

-- A users row may now only be created with id = auth.uid() (the trigger always
-- supplies it). Drop the autogenerated default so a divergent id can never be minted.
alter table public.users alter column id drop default;
