/**
 * GENERATED — the Schema.org `Organization` subtree closure, plus `WebSite`.
 *
 * Derived from the official vocabulary, NOT hand-listed:
 *   curl -sSL https://schema.org/version/latest/schemaorg-current-https.jsonld
 *   transitive closure of rdfs:subClassOf from `Organization`, union { WebSite }
 *   generated 2026-07-29 · schema.org current · 187 types
 *
 * DO NOT filter nodes by `@type` when regenerating. The first generator required
 * `@type == 'rdfs:Class'` and silently dropped 19 genuine `MedicalBusiness` subclasses — `Dermatology`,
 * `Physiotherapy`, `Pediatric`, `PrimaryCare`, `Psychiatric`, `Nursing` and the rest — because those
 * nodes are typed `schema:MedicalSpecialty`. A medical practice using the type schema.org and Google's
 * health guidance tell it to use got a false `missing_entity_link` and lost 3 points, while its
 * siblings `MedicalClinic` and `Dentist` worked, which is what made the hole invisible. Follow the
 * `subClassOf` edges regardless of node `@type`.
 *
 * WHY A CLOSURE AND NOT A LIST. Three hand-curated attempts each missed shapes the audience ships:
 * exact-match on two names missed `LocalBusiness`; a 13-name list missed `Plumber` — the example its
 * own comment cited; and the first "closure" missed the medical specialties above.
 *
 * `Person` is deliberately absent: §5 asks whether the site declares an ORGANISATION, and a solo
 * author is a different signal (FU-4, with the `sameAs` refinement).
 *
 * Regenerate when a Schema.org release changes the Organization subtree. A stale copy UNDER-credits
 * rather than over-credits — the safe direction, since a false positive silently removes a true
 * finding while a false negative adds a visible one.
 */
export const SCHEMA_ORG_ORGANIZATION_TYPES: readonly string[] = [
  'AccountingService',
  'AdultEntertainment',
  'Airline',
  'AmusementPark',
  'AnimalShelter',
  'ArchiveOrganization',
  'ArtGallery',
  'Attorney',
  'AutoBodyShop',
  'AutoDealer',
  'AutoPartsStore',
  'AutoRental',
  'AutoRepair',
  'AutoWash',
  'AutomatedTeller',
  'AutomotiveBusiness',
  'Bakery',
  'BankOrCreditUnion',
  'BarOrPub',
  'BeautySalon',
  'BedAndBreakfast',
  'BikeStore',
  'BookStore',
  'BowlingAlley',
  'Brewery',
  'CafeOrCoffeeShop',
  'Campground',
  'Casino',
  'ChildCare',
  'ClothingStore',
  'CollegeOrUniversity',
  'ComedyClub',
  'CommunityHealth',
  'ComputerStore',
  'Consortium',
  'ConvenienceStore',
  'Cooperative',
  'Corporation',
  'CovidTestingFacility',
  'DanceGroup',
  'DaySpa',
  'Dentist',
  'DepartmentStore',
  'Dermatology',
  'DiagnosticLab',
  'DietNutrition',
  'Distillery',
  'DryCleaningOrLaundry',
  'EducationalOrganization',
  'Electrician',
  'ElectronicsStore',
  'ElementarySchool',
  'Emergency',
  'EmergencyService',
  'EmploymentAgency',
  'EntertainmentBusiness',
  'ExerciseGym',
  'FastFoodRestaurant',
  'FinancialService',
  'FireStation',
  'Florist',
  'FoodEstablishment',
  'FundingAgency',
  'FundingScheme',
  'FurnitureStore',
  'GardenStore',
  'GasStation',
  'GeneralContractor',
  'Geriatric',
  'GolfCourse',
  'GovernmentOffice',
  'GovernmentOrganization',
  'GroceryStore',
  'Gynecologic',
  'HVACBusiness',
  'HairSalon',
  'HardwareStore',
  'HealthAndBeautyBusiness',
  'HealthClub',
  'HighSchool',
  'HobbyShop',
  'HomeAndConstructionBusiness',
  'HomeGoodsStore',
  'Hospital',
  'Hostel',
  'Hotel',
  'HousePainter',
  'IceCreamShop',
  'IndividualPhysician',
  'InsuranceAgency',
  'InternetCafe',
  'JewelryStore',
  'LegalService',
  'Library',
  'LibrarySystem',
  'LiquorStore',
  'LocalBusiness',
  'Locksmith',
  'LodgingBusiness',
  'MedicalBusiness',
  'MedicalClinic',
  'MedicalOrganization',
  'MensClothingStore',
  'MiddleSchool',
  'Midwifery',
  'MobilePhoneStore',
  'Motel',
  'MotorcycleDealer',
  'MotorcycleRepair',
  'MovieRentalStore',
  'MovieTheater',
  'MovingCompany',
  'MusicGroup',
  'MusicStore',
  'NGO',
  'NailSalon',
  'NewsMediaOrganization',
  'NightClub',
  'Notary',
  'Nursing',
  'Obstetric',
  'OfficeEquipmentStore',
  'Oncologic',
  'OnlineBusiness',
  'OnlineMarketplace',
  'OnlineStore',
  'Optician',
  'Optometric',
  'Organization',
  'Otolaryngologic',
  'OutletStore',
  'PawnShop',
  'Pediatric',
  'PerformingGroup',
  'PetStore',
  'Pharmacy',
  'Physician',
  'PhysiciansOffice',
  'Physiotherapy',
  'PlasticSurgery',
  'Plumber',
  'Podiatric',
  'PoliceStation',
  'PoliticalParty',
  'PostOffice',
  'Preschool',
  'PrimaryCare',
  'ProfessionalService',
  'Project',
  'Psychiatric',
  'PublicHealth',
  'PublicSwimmingPool',
  'RadioStation',
  'RealEstateAgent',
  'RecyclingCenter',
  'ResearchOrganization',
  'ResearchProject',
  'Resort',
  'Restaurant',
  'RoofingContractor',
  'School',
  'SearchRescueOrganization',
  'SelfStorage',
  'ShoeStore',
  'ShoppingCenter',
  'SkiResort',
  'SportingGoodsStore',
  'SportsActivityLocation',
  'SportsClub',
  'SportsOrganization',
  'SportsTeam',
  'StadiumOrArena',
  'Store',
  'TattooParlor',
  'TelevisionStation',
  'TennisComplex',
  'TheaterGroup',
  'TireShop',
  'TouristInformationCenter',
  'ToyStore',
  'TravelAgency',
  'VacationRental',
  'VeterinaryCare',
  'WebSite',
  'WholesaleStore',
  'Winery',
  'WorkersUnion',
] as const;
